### ISSUE TITLE
Precision of this device

### ISSUE THREAD

**Issue by simonachmueller** [dilshan/star-pointer#1]
Hi, I came across your project from latest hackaday newsletter and find it very interesting!

I was thinking about something similar before, mostly about placing a smartphone on the telescope and find or write a program to read sensors and simulate a mount controller like you did with Meade LX200 protocol.

I'm wandering about the precision of your device. Did you try to use it together with properly aligned GoTo mount in order to calculate a difference between an in-fact position and computed based on magnetometer and accelerometer? Or compare it with what you see through a telescope?

**Comment by dilshan** [comment]
Hi @simonachmueller, Thank you for your interest in this project. 

This unit designs to work as a finder scope. Due to the limited accuracy of the sensors, we cannot pinpoint the telescope to the target object using this.

I use this sensor kit as a finder scope replacement. I live in an area with a lot of light pollution, and therefore, using the optical finder scope is quite difficult (especially during deep sky observing sessions). 

At the testing stages, we attached this unit to the Celestron Omni XLT 150R telescope and verified the results with NexStar 8SE. We got very close results and the experience is really positive compared to the optical finder scope.

**But simply, this version of the sensor kit cannot replace the GoTo mount.**
